import { type Address } from "viem";

/**
 * Auto-generated by `npm run fork:deploy`.
 * Do not edit by hand — re-run deploy after restarting the fork node.
 */
export const LOCAL_FORK_DEPLOYMENT = {
  lendingModule: "0x07DfE23A3701Dac8bD23E25DE4589f8B28c42400" as Address,
  whitelist: "0xce25C5F81d97A575563DBc97f2eA6E9A5a9E28ff" as Address,
  oracle: "0x6e456Fc6472785bda9b6827538529186a4eC5b65" as Address,
  v3Adapter: "0x4E2F7a2f76DF65520cd1C23E8D6937eB26661804" as Address,
  v4Adapter: "0xaBF8a8e75011712FD0FEc3a15a2397F9d862763C" as Address,
  debtAsset: "0x1F22fF74176ffd6485b067330642D0c27e92d9A6" as Address,
  v3Npm: "0xC36442b4a4522E871399CD717aBDD847Ab11FE88" as Address,
  v4Npm: "0xbD216513d74C8cf14cf4747E6AaA6420FF64ee9e" as Address,
  v4StateView: "0x7fFE42C4a5DEeA5b0feC41C94C136Cf115597227" as Address,
  factory: "0x1F98431c8aD98523631AE4a59f267346ea31F984" as Address,
  updatedAt: "2026-09-15T10:25:22.286Z",
} as const;
