export const oracleAbi = [
  {
    type: "function",
    name: "getPositionValueUsd",
    stateMutability: "view",
    inputs: [
      { name: "version", type: "uint8" },
      { name: "tokenId", type: "uint256" },
    ],
    outputs: [{ name: "valueUsd", type: "uint256" }],
  },
  {
    type: "function",
    name: "getTokenPriceUsd",
    stateMutability: "view",
    inputs: [{ name: "token", type: "address" }],
    outputs: [{ name: "priceUsd", type: "uint256" }],
  },
] as const;

export const adapterAbi = [
  {
    type: "function",
    name: "getPositionMeta",
    stateMutability: "view",
    inputs: [{ name: "tokenId", type: "uint256" }],
    outputs: [
      { name: "token0", type: "address" },
      { name: "token1", type: "address" },
      { name: "poolId", type: "bytes32" },
      { name: "tickLower", type: "int24" },
      { name: "tickUpper", type: "int24" },
      { name: "liquidity", type: "uint128" },
    ],
  },
  {
    type: "function",
    name: "owns",
    stateMutability: "view",
    inputs: [{ name: "tokenId", type: "uint256" }],
    outputs: [{ name: "", type: "bool" }],
  },
  {
    type: "function",
    name: "getAmountsForValuation",
    stateMutability: "view",
    inputs: [
      { name: "tokenId", type: "uint256" },
      { name: "sqrtPriceX96", type: "uint160" },
    ],
    outputs: [
      { name: "amount0", type: "uint256" },
      { name: "amount1", type: "uint256" },
    ],
  },
  {
    type: "function",
    name: "getPoolSqrtPriceX96",
    stateMutability: "view",
    inputs: [{ name: "tokenId", type: "uint256" }],
    outputs: [{ name: "sqrtPriceX96", type: "uint160" }],
  },
  {
    type: "function",
    name: "positionManager",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
  },
  {
    type: "function",
    name: "npm",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
  },
] as const;

export const whitelistAbi = [
  {
    type: "function",
    name: "getPoolConfig",
    stateMutability: "view",
    inputs: [
      { name: "version", type: "uint8" },
      { name: "poolId", type: "bytes32" },
    ],
    outputs: [
      {
        name: "",
        type: "tuple",
        components: [
          { name: "allowed", type: "bool" },
          { name: "ltvBps", type: "uint16" },
          { name: "liquidationThresholdBps", type: "uint16" },
          { name: "liquidationBonusBps", type: "uint16" },
        ],
      },
    ],
  },
  {
    type: "function",
    name: "isDebtAssetAllowed",
    stateMutability: "view",
    inputs: [{ name: "asset", type: "address" }],
    outputs: [{ name: "", type: "bool" }],
  },
] as const;

export const erc721Abi = [
  {
    type: "function",
    name: "approve",
    stateMutability: "nonpayable",
    inputs: [
      { name: "to", type: "address" },
      { name: "tokenId", type: "uint256" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "getApproved",
    stateMutability: "view",
    inputs: [{ name: "tokenId", type: "uint256" }],
    outputs: [{ name: "", type: "address" }],
  },
  {
    type: "function",
    name: "setApprovalForAll",
    stateMutability: "nonpayable",
    inputs: [
      { name: "operator", type: "address" },
      { name: "approved", type: "bool" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "isApprovedForAll",
    stateMutability: "view",
    inputs: [
      { name: "owner", type: "address" },
      { name: "operator", type: "address" },
    ],
    outputs: [{ name: "", type: "bool" }],
  },
  {
    type: "function",
    name: "ownerOf",
    stateMutability: "view",
    inputs: [{ name: "tokenId", type: "uint256" }],
    outputs: [{ name: "", type: "address" }],
  },
  {
    type: "function",
    name: "balanceOf",
    stateMutability: "view",
    inputs: [{ name: "owner", type: "address" }],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "tokenOfOwnerByIndex",
    stateMutability: "view",
    inputs: [
      { name: "owner", type: "address" },
      { name: "index", type: "uint256" },
    ],
    outputs: [{ name: "", type: "uint256" }],
  },
] as const;

export const v3NpmAbi = [
  ...erc721Abi,
  {
    type: "function",
    name: "positions",
    stateMutability: "view",
    inputs: [{ name: "tokenId", type: "uint256" }],
    outputs: [
      { name: "nonce", type: "uint96" },
      { name: "operator", type: "address" },
      { name: "token0", type: "address" },
      { name: "token1", type: "address" },
      { name: "fee", type: "uint24" },
      { name: "tickLower", type: "int24" },
      { name: "tickUpper", type: "int24" },
      { name: "liquidity", type: "uint128" },
      { name: "feeGrowthInside0LastX128", type: "uint256" },
      { name: "feeGrowthInside1LastX128", type: "uint256" },
      { name: "tokensOwed0", type: "uint128" },
      { name: "tokensOwed1", type: "uint128" },
    ],
  },
] as const;

export const v4NpmAbi = [
  ...erc721Abi,
  {
    type: "function",
    name: "getPoolAndPositionInfo",
    stateMutability: "view",
    inputs: [{ name: "tokenId", type: "uint256" }],
    outputs: [
      {
        name: "poolKey",
        type: "tuple",
        components: [
          { name: "currency0", type: "address" },
          { name: "currency1", type: "address" },
          { name: "fee", type: "uint24" },
          { name: "tickSpacing", type: "int24" },
          { name: "hooks", type: "address" },
        ],
      },
      { name: "info", type: "uint256" },
    ],
  },
  {
    type: "function",
    name: "getPositionLiquidity",
    stateMutability: "view",
    inputs: [{ name: "tokenId", type: "uint256" }],
    outputs: [{ name: "liquidity", type: "uint128" }],
  },
] as const;

export const erc20Abi = [
  {
    type: "function",
    name: "approve",
    stateMutability: "nonpayable",
    inputs: [
      { name: "spender", type: "address" },
      { name: "amount", type: "uint256" },
    ],
    outputs: [{ name: "", type: "bool" }],
  },
  {
    type: "function",
    name: "allowance",
    stateMutability: "view",
    inputs: [
      { name: "owner", type: "address" },
      { name: "spender", type: "address" },
    ],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "decimals",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint8" }],
  },
  {
    type: "function",
    name: "symbol",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "string" }],
  },
  {
    type: "function",
    name: "balanceOf",
    stateMutability: "view",
    inputs: [{ name: "account", type: "address" }],
    outputs: [{ name: "", type: "uint256" }],
  },
] as const;

/** MarketLendingModule — per-pair Circle USDC pools (Sepolia markets stack). */
export const marketLendingAbi = [
  {
    type: "function",
    name: "usdc",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
  },
  {
    type: "function",
    name: "pairIdOf",
    stateMutability: "pure",
    inputs: [
      { name: "tokenA", type: "address" },
      { name: "tokenB", type: "address" },
    ],
    outputs: [{ name: "", type: "bytes32" }],
  },
  {
    type: "function",
    name: "pools",
    stateMutability: "view",
    inputs: [{ name: "pairId", type: "bytes32" }],
    outputs: [
      { name: "cash", type: "uint256" },
      { name: "totalShares", type: "uint256" },
      { name: "totalPrincipal", type: "uint256" },
      { name: "totalAccruedInterest", type: "uint256" },
    ],
  },
  {
    type: "function",
    name: "cashBalance",
    stateMutability: "view",
    inputs: [{ name: "pairId", type: "bytes32" }],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "totalAssets",
    stateMutability: "view",
    inputs: [{ name: "pairId", type: "bytes32" }],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "utilizationBps",
    stateMutability: "view",
    inputs: [{ name: "pairId", type: "bytes32" }],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "availableToBorrow",
    stateMutability: "view",
    inputs: [{ name: "pairId", type: "bytes32" }],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "availableToWithdraw",
    stateMutability: "view",
    inputs: [{ name: "pairId", type: "bytes32" }],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "maxUtilizationBps",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint16" }],
  },
  {
    type: "function",
    name: "defaultLtvBps",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint16" }],
  },
  {
    type: "function",
    name: "fallbackLenderApyBps",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint16" }],
  },
  {
    type: "function",
    name: "getLenderApyBps",
    stateMutability: "view",
    inputs: [{ name: "pairId", type: "bytes32" }],
    outputs: [{ name: "", type: "uint16" }],
  },
  {
    type: "function",
    name: "sharesOf",
    stateMutability: "view",
    inputs: [
      { name: "pairId", type: "bytes32" },
      { name: "lender", type: "address" },
    ],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "vaultOf",
    stateMutability: "view",
    inputs: [{ name: "pairId", type: "bytes32" }],
    outputs: [{ name: "", type: "address" }],
  },
  {
    type: "function",
    name: "convertToAssets",
    stateMutability: "view",
    inputs: [
      { name: "pairId", type: "bytes32" },
      { name: "shares", type: "uint256" },
    ],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "convertToShares",
    stateMutability: "view",
    inputs: [
      { name: "pairId", type: "bytes32" },
      { name: "assets", type: "uint256" },
    ],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "previewBorrow",
    stateMutability: "view",
    inputs: [
      { name: "version", type: "uint8" },
      { name: "tokenId", type: "uint256" },
    ],
    outputs: [
      { name: "pairId", type: "bytes32" },
      { name: "borrowAprBps", type: "uint16" },
      { name: "lenderApyBps", type: "uint16" },
      { name: "collateralValueUsd", type: "uint256" },
      { name: "maxBorrowUsdc", type: "uint256" },
      { name: "poolAvailable", type: "uint256" },
    ],
  },
  {
    type: "function",
    name: "currentDebt",
    stateMutability: "view",
    inputs: [{ name: "loanId", type: "uint256" }],
    outputs: [
      { name: "principal", type: "uint256" },
      { name: "interest", type: "uint256" },
      { name: "total", type: "uint256" },
    ],
  },
  {
    type: "function",
    name: "getBorrowerLoans",
    stateMutability: "view",
    inputs: [{ name: "borrower", type: "address" }],
    outputs: [{ name: "", type: "uint256[]" }],
  },
  {
    type: "function",
    name: "loans",
    stateMutability: "view",
    inputs: [{ name: "", type: "uint256" }],
    outputs: [
      { name: "borrower", type: "address" },
      { name: "version", type: "uint8" },
      { name: "tokenId", type: "uint256" },
      { name: "pairId", type: "bytes32" },
      { name: "principal", type: "uint256" },
      { name: "accruedInterest", type: "uint256" },
      { name: "borrowAprBps", type: "uint16" },
      { name: "lastAccrual", type: "uint64" },
      { name: "ltvBps", type: "uint16" },
      { name: "liquidationThresholdBps", type: "uint16" },
      { name: "active", type: "bool" },
    ],
  },
  {
    type: "function",
    name: "isLiquidatable",
    stateMutability: "view",
    inputs: [{ name: "loanId", type: "uint256" }],
    outputs: [{ name: "", type: "bool" }],
  },
  {
    type: "function",
    name: "previewLiquidation",
    stateMutability: "view",
    inputs: [{ name: "loanId", type: "uint256" }],
    outputs: [
      { name: "liquidatable", type: "bool" },
      { name: "token0", type: "address" },
      { name: "token1", type: "address" },
      { name: "amount0", type: "uint256" },
      { name: "amount1", type: "uint256" },
      { name: "estimatedUsdc", type: "uint256" },
      { name: "debt", type: "uint256" },
      { name: "shortfall", type: "uint256" },
    ],
  },
  {
    type: "function",
    name: "liquidate",
    stateMutability: "nonpayable",
    inputs: [{ name: "loanId", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "findFirstLiquidatableLoan",
    stateMutability: "view",
    inputs: [],
    outputs: [
      { name: "found", type: "bool" },
      { name: "loanId", type: "uint256" },
    ],
  },
  {
    type: "function",
    name: "authorizedLiquidators",
    stateMutability: "view",
    inputs: [{ name: "account", type: "address" }],
    outputs: [{ name: "", type: "bool" }],
  },
  {
    type: "function",
    name: "setAuthorizedLiquidator",
    stateMutability: "nonpayable",
    inputs: [
      { name: "account", type: "address" },
      { name: "allowed", type: "bool" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "defaultLiquidationThresholdBps",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint16" }],
  },
  {
    type: "function",
    name: "swapRouter",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
  },
  {
    type: "function",
    name: "setSwapRouter",
    stateMutability: "nonpayable",
    inputs: [{ name: "router", type: "address" }],
    outputs: [],
  },
  {
    type: "function",
    name: "setDefaultLiquidationThresholdBps",
    stateMutability: "nonpayable",
    inputs: [{ name: "bps", type: "uint16" }],
    outputs: [],
  },
  {
    type: "function",
    name: "adapters",
    stateMutability: "view",
    inputs: [{ name: "", type: "uint8" }],
    outputs: [{ name: "", type: "address" }],
  },
  {
    type: "function",
    name: "lendUsdc",
    stateMutability: "nonpayable",
    inputs: [
      { name: "pairId", type: "bytes32" },
      { name: "assets", type: "uint256" },
    ],
    outputs: [{ name: "shares", type: "uint256" }],
  },
  {
    type: "function",
    name: "lendToPair",
    stateMutability: "nonpayable",
    inputs: [
      { name: "tokenA", type: "address" },
      { name: "tokenB", type: "address" },
      { name: "assets", type: "uint256" },
    ],
    outputs: [{ name: "shares", type: "uint256" }],
  },
  {
    type: "function",
    name: "withdrawLender",
    stateMutability: "nonpayable",
    inputs: [
      { name: "pairId", type: "bytes32" },
      { name: "shares", type: "uint256" },
    ],
    outputs: [{ name: "assets", type: "uint256" }],
  },
  {
    type: "function",
    name: "borrowWithCollateral",
    stateMutability: "nonpayable",
    inputs: [
      { name: "version", type: "uint8" },
      { name: "tokenId", type: "uint256" },
      { name: "amount", type: "uint256" },
    ],
    outputs: [{ name: "loanId", type: "uint256" }],
  },
  {
    type: "function",
    name: "borrowMore",
    stateMutability: "nonpayable",
    inputs: [
      { name: "loanId", type: "uint256" },
      { name: "amount", type: "uint256" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "repay",
    stateMutability: "nonpayable",
    inputs: [
      { name: "loanId", type: "uint256" },
      { name: "amount", type: "uint256" },
    ],
    outputs: [{ name: "paid", type: "uint256" }],
  },
  {
    type: "function",
    name: "repayAndWithdraw",
    stateMutability: "nonpayable",
    inputs: [
      { name: "loanId", type: "uint256" },
      { name: "amount", type: "uint256" },
    ],
    outputs: [{ name: "paid", type: "uint256" }],
  },
  {
    type: "function",
    name: "withdrawCollateral",
    stateMutability: "nonpayable",
    inputs: [{ name: "loanId", type: "uint256" }],
    outputs: [],
  },
  { type: "error", name: "AdapterMissing", inputs: [] },
  { type: "error", name: "ZeroAmount", inputs: [] },
  { type: "error", name: "ZeroAddress", inputs: [] },
  { type: "error", name: "InvalidBps", inputs: [] },
  { type: "error", name: "ThresholdBelowLtv", inputs: [] },
  { type: "error", name: "SwapRouterNotSet", inputs: [] },
  { type: "error", name: "NotLiquidationAuthority", inputs: [] },
  {
    type: "error",
    name: "StillHealthy",
    inputs: [{ name: "loanId", type: "uint256" }],
  },
  {
    type: "error",
    name: "PairNotSupported",
    inputs: [{ name: "pairId", type: "bytes32" }],
  },
  {
    type: "error",
    name: "PositionAlreadyUsed",
    inputs: [
      { name: "version", type: "uint8" },
      { name: "tokenId", type: "uint256" },
    ],
  },
  {
    type: "error",
    name: "LoanInactive",
    inputs: [{ name: "loanId", type: "uint256" }],
  },
  {
    type: "error",
    name: "NotBorrower",
    inputs: [
      { name: "caller", type: "address" },
      { name: "borrower", type: "address" },
    ],
  },
  {
    type: "error",
    name: "ExceedsLTV",
    inputs: [
      { name: "requested", type: "uint256" },
      { name: "maxAllowed", type: "uint256" },
    ],
  },
  {
    type: "error",
    name: "ExceedsUtilization",
    inputs: [
      { name: "utilizationBps", type: "uint256" },
      { name: "maxBps", type: "uint16" },
    ],
  },
  {
    type: "error",
    name: "InsufficientPoolCash",
    inputs: [
      { name: "requested", type: "uint256" },
      { name: "available", type: "uint256" },
    ],
  },
  { type: "error", name: "InsufficientShares", inputs: [] },
  {
    type: "error",
    name: "DebtRemaining",
    inputs: [
      { name: "loanId", type: "uint256" },
      { name: "remaining", type: "uint256" },
    ],
  },
  {
    type: "function",
    name: "owner",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
  },
  {
    type: "function",
    name: "paused",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "bool" }],
  },
  {
    type: "function",
    name: "oracle",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
  },
  {
    type: "function",
    name: "borrowRateConfig",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
  },
  {
    type: "function",
    name: "apySource",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
  },
  {
    type: "function",
    name: "setAdapters",
    stateMutability: "nonpayable",
    inputs: [
      { name: "v3", type: "address" },
      { name: "v4", type: "address" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "setOracle",
    stateMutability: "nonpayable",
    inputs: [{ name: "oracle_", type: "address" }],
    outputs: [],
  },
  {
    type: "function",
    name: "setBorrowRateConfig",
    stateMutability: "nonpayable",
    inputs: [{ name: "config", type: "address" }],
    outputs: [],
  },
  {
    type: "function",
    name: "setApySource",
    stateMutability: "nonpayable",
    inputs: [{ name: "source", type: "address" }],
    outputs: [],
  },
  {
    type: "function",
    name: "setFallbackLenderApyBps",
    stateMutability: "nonpayable",
    inputs: [{ name: "bps", type: "uint16" }],
    outputs: [],
  },
  {
    type: "function",
    name: "setMaxUtilizationBps",
    stateMutability: "nonpayable",
    inputs: [{ name: "bps", type: "uint16" }],
    outputs: [],
  },
  {
    type: "function",
    name: "setLiquidationFeeBps",
    stateMutability: "nonpayable",
    inputs: [{ name: "bps", type: "uint16" }],
    outputs: [],
  },
  {
    type: "function",
    name: "liquidationFeeBps",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint16" }],
  },
  {
    type: "function",
    name: "setFeeTo",
    stateMutability: "nonpayable",
    inputs: [{ name: "account", type: "address" }],
    outputs: [],
  },
  {
    type: "function",
    name: "feeTo",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
  },
  {
    type: "function",
    name: "setDefaultLtvBps",
    stateMutability: "nonpayable",
    inputs: [{ name: "bps", type: "uint16" }],
    outputs: [],
  },
  {
    type: "function",
    name: "pause",
    stateMutability: "nonpayable",
    inputs: [],
    outputs: [],
  },
  {
    type: "function",
    name: "unpause",
    stateMutability: "nonpayable",
    inputs: [],
    outputs: [],
  },
  {
    type: "event",
    name: "Supplied",
    inputs: [
      { name: "pairId", type: "bytes32", indexed: true },
      { name: "lender", type: "address", indexed: true },
      { name: "assets", type: "uint256", indexed: false },
      { name: "shares", type: "uint256", indexed: false },
    ],
  },
  {
    type: "event",
    name: "WithdrawnSupply",
    inputs: [
      { name: "pairId", type: "bytes32", indexed: true },
      { name: "lender", type: "address", indexed: true },
      { name: "assets", type: "uint256", indexed: false },
      { name: "shares", type: "uint256", indexed: false },
    ],
  },
] as const;

export const borrowRateConfigAbi = [
  {
    type: "function",
    name: "owner",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
  },
  {
    type: "function",
    name: "setPair",
    stateMutability: "nonpayable",
    inputs: [
      { name: "tokenA", type: "address" },
      { name: "tokenB", type: "address" },
      { name: "aprBps", type: "uint16" },
      { name: "enabled", type: "bool" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "isPairSupported",
    stateMutability: "view",
    inputs: [{ name: "pairId", type: "bytes32" }],
    outputs: [{ name: "", type: "bool" }],
  },
  {
    type: "function",
    name: "getBorrowAprBps",
    stateMutability: "view",
    inputs: [{ name: "pairId", type: "bytes32" }],
    outputs: [{ name: "", type: "uint16" }],
  },
  {
    type: "function",
    name: "pairIdOf",
    stateMutability: "view",
    inputs: [
      { name: "tokenA", type: "address" },
      { name: "tokenB", type: "address" },
    ],
    outputs: [{ name: "", type: "bytes32" }],
  },
  { type: "error", name: "InvalidApr", inputs: [] },
  { type: "error", name: "ZeroAddress", inputs: [] },
] as const;

export const staticApySourceAbi = [
  {
    type: "function",
    name: "owner",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
  },
  {
    type: "function",
    name: "defaultApyBps",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint16" }],
  },
  {
    type: "function",
    name: "setDefaultApyBps",
    stateMutability: "nonpayable",
    inputs: [{ name: "bps", type: "uint16" }],
    outputs: [],
  },
  {
    type: "function",
    name: "setApyBps",
    stateMutability: "nonpayable",
    inputs: [
      { name: "marketId", type: "bytes32" },
      { name: "bps", type: "uint16" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "getLenderApyBps",
    stateMutability: "view",
    inputs: [{ name: "marketId", type: "bytes32" }],
    outputs: [{ name: "", type: "uint16" }],
  },
] as const;

export const oracleAdminAbi = [
  {
    type: "function",
    name: "owner",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
  },
  {
    type: "function",
    name: "feeds",
    stateMutability: "view",
    inputs: [{ name: "", type: "address" }],
    outputs: [{ name: "", type: "address" }],
  },
  {
    type: "function",
    name: "maxPriceAge",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "maxPoolDeviationBps",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint16" }],
  },
  {
    type: "function",
    name: "adapters",
    stateMutability: "view",
    inputs: [{ name: "", type: "uint8" }],
    outputs: [{ name: "", type: "address" }],
  },
  {
    type: "function",
    name: "getTokenPriceUsd",
    stateMutability: "view",
    inputs: [{ name: "token", type: "address" }],
    outputs: [{ name: "priceUsd", type: "uint256" }],
  },
  {
    type: "function",
    name: "setFeed",
    stateMutability: "nonpayable",
    inputs: [
      { name: "token", type: "address" },
      { name: "feed", type: "address" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "setAdapter",
    stateMutability: "nonpayable",
    inputs: [
      { name: "version", type: "uint8" },
      { name: "adapter", type: "address" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "setMaxPriceAge",
    stateMutability: "nonpayable",
    inputs: [{ name: "age", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "setTokenMaxPriceAge",
    stateMutability: "nonpayable",
    inputs: [
      { name: "token", type: "address" },
      { name: "age", type: "uint256" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "setMaxPoolDeviationBps",
    stateMutability: "nonpayable",
    inputs: [{ name: "bps", type: "uint16" }],
    outputs: [],
  },
] as const;

/** Per-pair ERC-4626 PairVault (idle USDC + share token). */
export const pairVaultAbi = [
  {
    type: "function",
    name: "asset",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
  },
  {
    type: "function",
    name: "pairId",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "bytes32" }],
  },
  {
    type: "function",
    name: "idleAssets",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "totalAssets",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "balanceOf",
    stateMutability: "view",
    inputs: [{ name: "account", type: "address" }],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "convertToAssets",
    stateMutability: "view",
    inputs: [{ name: "shares", type: "uint256" }],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "convertToShares",
    stateMutability: "view",
    inputs: [{ name: "assets", type: "uint256" }],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "maxWithdraw",
    stateMutability: "view",
    inputs: [{ name: "owner", type: "address" }],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "deposit",
    stateMutability: "nonpayable",
    inputs: [
      { name: "assets", type: "uint256" },
      { name: "receiver", type: "address" },
    ],
    outputs: [{ name: "shares", type: "uint256" }],
  },
  {
    type: "function",
    name: "withdraw",
    stateMutability: "nonpayable",
    inputs: [
      { name: "assets", type: "uint256" },
      { name: "receiver", type: "address" },
      { name: "owner", type: "address" },
    ],
    outputs: [{ name: "shares", type: "uint256" }],
  },
  {
    type: "function",
    name: "redeem",
    stateMutability: "nonpayable",
    inputs: [
      { name: "shares", type: "uint256" },
      { name: "receiver", type: "address" },
      { name: "owner", type: "address" },
    ],
    outputs: [{ name: "assets", type: "uint256" }],
  },
] as const;
